### ISSUE TITLE
Updated variable not set in multi-stage pipelines?

### ISSUE THREAD

**Issue by SWarnberg** [oscarvantol/azure-pipelines-version-increment#4]
Hi

I'm using this task to update a pipeline version variable, which works fine. However, when using a multi-stage pipeline, the variable that is updated in one stage isn't updated in the next stage. Is this a know behavior, and what would be the solution for it?

Staffan

**Comment by oscarvantol** [comment]
Hi @SWarnberg,

The variable is set but will only be available in the current stage, in a multi stage pipeline this would cause the variable to fall back to the original value that it had when the pipeline started. A workaround would be to use output variables as described in: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable

I tried this in a simple setup and I think this might help your scenario. Here is the yaml for it:

```
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: one
    jobs:
      - job: job1
        steps:
        - task: version-increment-task@0
          inputs:
            incrementType: patch
            versionVariable: 'version'
        - script: echo '##vso[task.setvariable variable=version;isOutput=true]$(version)'
          name: job1_outputs
   
  - stage: two
    dependsOn: one
    jobs:
      - job: job2
        variables:
          versionFromStageOne: $[stageDependencies.one.job1.outputs['job1_outputs.version']]
        steps:
        - script: echo "stage two" versionFromOutput=$(versionFromStageOne)

```

Let me know if this helps.
